### ISSUE TITLE
Cannot read property 'left' of null

### ISSUE THREAD

**Issue by jliebrand** [mfogel/polygon-clipping#36] opened 2018-09-26 07:55 UTC
Reproduce case: https://repl.it/repls/TangibleHoneydewFiber

As far as I can make out, the input geometry should be valid, but it clearly barfs on some aspect of it... Still trying find which of the polygons is causing the problem...

**Comment by jliebrand** [comment] 2018-09-26 10:55
Another case where the same exception is thrown for a different dataset:

https://repl.it/repls/IdenticalBuzzingTruespace

**Comment by jliebrand** [comment] 2018-09-26 11:02
Furthermore, on the first dataset, if I try to narrow down which geom is causing the problems, I see this;
```
polygonClipping.union(featureCollection().slice(2,3))

Uncaught Error: Input has more than two coordinates. Only 2-dimensional polygons supported.
```

Not sure if that's related at all though?

**Comment by jliebrand** [comment] 2018-09-26 12:00
I suspect this might be related to issue #29 and I am curious about this line of code (from the fix for that bug):

https://github.com/mfogel/polygon-clipping/blob/master/src/segment.js#L58

Shouldn't that be
```
if (a.isVertical !== b.isVertical) return (a.isVertical ? -1 : 1)
```

At the moment it will return just a.isVertical, which is either true or false, and when false the compare function will thus claim the two segments are identical? Or is that actually the intention? (still wrapping my head around the algo and code)

**Comment by jliebrand** [comment] 2018-09-26 16:00
(note: my previous comment doesn't fix/change the issue. But it seemed odd)

**Comment by mfogel** [comment] 2018-09-28 16:06
Hi @jliebrand , thanks for the bug report

Not sure on any easy workarounds.... once I get a chance to deep dive into these shapes and understand what's going wrong I may be able to recommend a work-around. In the past rounding errors have often caused bugs like these, but looking at your shapes I see ~6 decimals not ~12, so I think rounding errors are probably not the cause of the problem, but can't say for sure at this point.

I don't have time to deep dive into this today, but might this weekend.

My process for debugging this will be:

1. transform the shapes you have in those two Repl.it examples into one or more failing end-to-end test cases. This means adding at least one directory to [this dir](https://github.com/mfogel/polygon-clipping/tree/master/test/end-to-end) with at least two files - `args.geojson` and `union.geojson`
1. simplify the failing test cases. Reduce the polygons in `args.geojson` to the simplest possible polygons that still trigger the bug.
1. step through the algorithm manually to try to figure out what's going wrong.

I'll use [this line](https://github.com/mfogel/polygon-clipping/blob/master/test/end-to-end.test.js#L9) to focus on one failing end-to-end test case at a time.

I'll use tools like [mapshaper.org](https://mapshaper.org/) and [geojsonhint](https://github.com/mapbox/geojsonhint) to visualize the shapes and makes sure they're well-formed.

If you want to help things along, if you can fork this project, make a branch and do the first one or two steps that'll save me time.

And - thanks for pointing out that bug in `Segment.compare` - it should be fixed now on master.

Cheers

**Comment by jliebrand** [comment] 2018-10-02 10:44
Great - I'll have a look at adding tests to cover this and try to get a minimum repro case

**Comment by jliebrand** [comment] 2018-10-02 10:45
Interesting - I can not reproduce the crash on master... it still crashes on the version from 30th aug (eg the released version), but it seems to work on the latest...

Time for an updated release?

**Comment by jliebrand** [comment] 2018-10-02 10:58
It seems this commit:
https://github.com/mfogel/polygon-clipping/commit/d0ce1ef0458d14be838b59b25554c4c5846954ed

Fixed this problem. We have a few more errors in our logs, I will check if those are also fixed with that commit or not. And if not, put some test cases in

**Comment by jliebrand** [comment] 2018-10-02 12:39
I'll leave this bug open until that commit is released, but it does indeed appear to have solved the problem.

There is however another bug where the input causes an infinite loop somewhere. I've raised a new issue (#38 ) and a PR to add a test case for it.

**Comment by mfogel** [comment] 2018-10-02 15:05
Glad to see it's already fixed! Thanks for tracking this further down @jliebrand 

To make sure the test suite covers this case, I added a test case to master anyway of a mostly-simplified geometry based off one of the ones you provided above, which triggers a failure on v0.8 but passes on master.

I'll release a v0.9 with this fix once the other open bugs are either fixed or understood to be a enough work to justify pushing them to v0.10

**Comment by jliebrand** [comment] 2018-10-07 13:32
I think I might have spoken too soon. Looks like these coordinates still cause this bug to trigger:

https://gist.github.com/jliebrand/8aa87238df614d1c5d456af98fd0ad49

**Comment by mfogel** [comment] 2018-10-16 18:32
@jliebrand sorry for the pause. I'll make time tonight / tomorrow to review at least some of the other open bugs & PR's and release a v0.9 regardless so that at least this fix can be pushed out to npm.

**Comment by mfogel** [comment] 2018-10-18 00:15
Just released v0.9 that has the fix to this in it.

**Comment by jliebrand** [comment] 2018-10-18 06:07
Did you see my comment 
https://github.com/mfogel/polygon-clipping/issues/36#issuecomment-427653925

Not sure 0.9 fixes that? Unless you made another change?

**Comment by mfogel** [comment] 2018-10-18 12:15
@jliebrand sorry missed your comment. I just verified it's still broken on those coordinates - reopening this bug.

**Comment by jliebrand** [comment] 2018-10-23 07:05
@mfogel how are things going with this (and the other) bugs?

**Comment by jliebrand** [comment] 2018-10-23 07:07
ps. it doesn't look like 0.9 is on npm yet?

**Comment by mfogel** [comment] 2018-10-23 10:31
I think [v0.9 is on npm](https://www.npmjs.com/package/polygon-clipping/v/0.9.0). (there is a mistake in the README on there, it says that v0.9 is still 'in development')

I should get a few hours to process through the open bugs on saturday and sunday. In general, if they turn out *not* to be floating-point rounding issues, they're a lot easier to fix.

**Comment by jliebrand** [comment] 2018-10-23 10:42
Ah great! I used npm-check to see if there was an update and it didn't report it. But that's probably because I have the module pointed directly to github. I'll have to keep that for now, as 0.9 does not have the guard against the eternal loop. But I'll update my package.json once the other bugs are fixed.

**Comment by mfogel** [comment] 2018-10-27 17:18
Ok, I've reduced the error condition to applying a `union` to these shapes:

```js
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [[0.0, 1.0], [0.0, 1.04], [0.08, 1.02], [0.14, 1.04], [0.0, 1.0]]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[[0.08, 1.02], [0.0, 1.0], [0.0, 1.04], [0.08, 1.02]]]
      }
    }
  ]
}
```

They look pretty harmless, but there are a few identical segments in those two polygons, which I suspect is triggering the bug. Stay tuned!

**Closed** 2018-10-27 18:45 UTC
Labels: bug
