### ISSUE TITLE
Collinear Edges causing issues with intersection

### ISSUE THREAD

**Issue by betovelandia** [mfogel/polygon-clipping#84] opened 2019-08-13 20:35 UTC
Here is the data:
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [6.5542, 4.4237],
            [6.5542, 4.4505],
            [6.5542, 4.4461],
            [6.5542, 4.4718],
            [6.5542, 4.4766],
            [6.5542, 4.4754],
            [6.5542, 4.4901],
            [6.5542, 4.5003],
            [6.5542, 4.5062],
            [6.4989, 4.5062],
            [6.4844, 4.5062],
            [6.5032, 4.5062],
            [6.5101, 4.5062],
            [6.4726, 4.5062],
            [6.4457, 4.5062],
            [6.3901, 4.5062],
            [6.3864, 4.5062],
            [6.4336, 4.5062],
            [6.4947, 4.5062],
            [6.4832, 4.4579],
            [6.5176, 4.4820],
            [6.5542, 4.4380],
            [6.5542, 4.3911],
            [6.5542, 4.3794],
            [6.5542, 4.3997],
            [6.5542, 4.4007],
            [6.5542, 4.4237]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [6.479, 4.454],
            [6.5642, 4.4100],
            [6.5642, 4.508],
            [6.380, 4.508],
            [6.380, 4.454]
          ]
        ]
      }
    }
  ]
}
```

The intersection is not catching the left side of the subject (green) or the one on the right side at the bottom also, clipping is blue and result is red:

![Screen Shot 2019-08-13 at 12 35 03 PM](https://user-images.githubusercontent.com/440908/62975395-1f266280-bdcf-11e9-8295-99807bf6062d.png)

**Comment by betovelandia** [comment] 2019-08-13 20:38
```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [6.5542, 4.4237],
            [6.5542, 4.4505],
            [6.5542, 4.4461],
            [6.5542, 4.4718],
            [6.5542, 4.4766],
            [6.5542, 4.4754],
            [6.5542, 4.4901],
            [6.5542, 4.5003],
            [6.5542, 4.5062],
            [6.4989, 4.5062],
            [6.4844, 4.5062],
            [6.5032, 4.5062],
            [6.5101, 4.5062],
            [6.4726, 4.5062],
            [6.4457, 4.5062],
            [6.3901, 4.5062],
            [6.3864, 4.5062],
            [6.4336, 4.5062],
            [6.4947, 4.5062],
            [6.4832, 4.4579],
            [6.5176, 4.4820],
            [6.5542, 4.4380],
            [6.5542, 4.3911],
            [6.5542, 4.3794],
            [6.5542, 4.3997],
            [6.5542, 4.4007],
            [6.5542, 4.4237]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [6.479, 4.454],
            [6.5642, 4.4100],
            [6.5642, 4.508],
            [6.380, 4.508],
            [6.380, 4.454]
          ]
        ]
      }
    }
  ]
}
```

**Comment by mfogel** [comment] 2019-08-16 00:01
Hi @betovelandia thanks for the bug report

I think what's going on is that the algorithm is discarding infinitely thin parts of polygons (by design). It sounds like you want to preserve them. I'm racking my brain for a way to do that with this library... not really coming up with anything.

To understand why infinitely thin parts of polygons are dropped, consider taking the difference of these two polygons: https://github.com/mfogel/polygon-clipping/blob/master/test/end-to-end/overlap-edges/args.geojson . I think most people would expect this to be the result: https://github.com/mfogel/polygon-clipping/blob/master/test/end-to-end/overlap-edges/difference.geojson . But if you kept infinitely thin parts of polygons around, those two disjoint polygons in the result would be connected by an infinitely thin line between them.

**Comment by betovelandia** [comment] 2019-08-19 16:30
I believe you are right and that they should not be included in the result, should we close this one?

**Comment by mfogel** [comment] 2019-08-19 22:10
Cool, yup - closing. cheers

**Closed by mfogel** 2019-08-19 22:10 UTC
